name: at_client
description: at_client is the Client SDK which provides the essential methods for building an app using the @protocol.
version: 1.0.1+10
repository: https://github.com/atsign-foundation/at_client_sdk
homepage: https://atsign.dev
documentation: https://atsign.dev/at_docs-dev_env/at_client/index.html

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0
  utf7: ^0.2.1
  crypton: ^2.0.1
  encrypt: ^5.0.0
  cron: ^0.2.2
  convert: ^2.1.1
  base2e15: ^0.3.0
  uuid: ^3.0.4
  crypto: ^3.0.0
  collection: ^1.14.12
  pedantic: ^1.8.0
  at_persistence_spec: ^1.0.1+3
  at_persistence_secondary_server: ^1.0.1+8
  at_lookup: ^1.0.0+8
  at_commons: ^1.0.1+8
  at_utils: ^1.0.1+8

dev_dependencies:
  test: ^1.6.0
