name: at_client
description: at_client is the Client SDK which provides the essential methods for building an app using the @protocol.
version: 2.0.3
repository: https://github.com/atsign-foundation/at_client_sdk
homepage: https://atsign.dev
documentation: https://atsign.dev/at_docs-dev_env/at_client/index.html

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  hive: ^2.0.4
  crypton: ^2.0.1
  encrypt: ^5.0.0
  cron: ^0.3.0
  convert: ^3.0.0
  uuid: ^3.0.4
  crypto: ^3.0.1
  collection: ^1.15.0
  pedantic: ^1.11.0
  archive: ^3.1.2
  http: ^0.13.3
  internet_connection_checker: 0.0.1+1
  at_persistence_spec: ^2.0.0
  at_persistence_secondary_server: ^2.0.3
  at_lookup: ^2.0.3
  at_utf7: ^1.0.0
  at_base2e15: ^1.0.0
  at_commons: ^2.0.3
  at_utils: ^2.0.3


dev_dependencies:
  test: ^1.17.2
  at_demo_data: ^0.0.3+1
