name: at_client
description: Client SDK for communicating with a secondary server
version: 1.0.0
homepage: https://atsign.dev

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0
  utf7: ^0.2.1
  hive: ^1.3.0
  crypton: ^1.1.0
  encrypt: ^4.0.2
  cron: ^0.2.2
  convert: ^2.1.1
  base2e15: ^0.3.0
  uuid: ^2.0.2
  at_persistence_secondary_server:
    git:
      url: git@github.com:atsign-foundation/at_server.git
      path: at_secondary/at_persistence_secondary_server
      ref: master
  at_lookup:
    git:
      url: git@github.com:atsign-foundation/at_libraries.git
      path: at_lookup
      ref: master

#dependency_overrides:
#  at_persistence_spec:
#    path: ../at_persistence_spec
#  at_persistence_secondary_server:
#    path: ../at_persistence_secondary_server
#  at_commons:
#    path: ../at_commons
#  at_utils:
#    path: ../at_utils
#  at_lookup:
#    path: ../at_lookup
dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0