name: at_client
description: at_client is the Client SDK which provides the essential methods for building an app using the @protocol.
version: 1.0.1+9
repository: https://github.com/atsign-foundation/at_client_sdk
homepage: https://atsign.dev
documentation: https://atsign.dev/at_docs-dev_env/at_client/index.html
publish_to: none

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0
  utf7: ^0.2.1
  crypton: ^2.0.1
  encrypt: ^5.0.0
  cron: ^0.2.2
  convert: ^2.1.1
  base2e15: ^0.3.0
  uuid: ^3.0.4
  crypto: ^3.0.0
  collection: ^1.14.12
  pedantic: ^1.8.0
  at_persistence_spec:
    path: ../../../trunk/at_server/at_persistence/at_persistence_spec
#    git:
#      url: https://github.com/atsign-foundation/at_server.git
#      path: at_persistence/at_persistence_spec
#      ref: trunk
#      version: ^1.0.1+3
      
  at_persistence_secondary_server:
    path: ../../../trunk/at_server/at_secondary/at_persistence_secondary_server
#    git:
#      url: https://github.com/atsign-foundation/at_server.git
#      path: at_secondary/at_persistence_secondary_server
#      ref: trunk
#      version: ^1.0.1+7
  at_lookup:
    path: ../../at_libraries/at_lookup
#    git:
#      url: https://github.com/atsign-foundation/at_libraries.git
#      path: at_lookup
#      ref: trunk
#      version: ^1.0.0+7
  at_commons:
    path: ../../at_tools/at_commons
#    git:
#      url: https://github.com/atsign-foundation/at_tools.git
#      path: at_commons
#      ref: trunk
#      version: ^1.0.1+7
  at_utils:
    path: ../../at_tools/at_utils
#    git:
#      url: https://github.com/atsign-foundation/at_tools.git
#      path: at_utils
#      ref: trunk
#      version: ^1.0.1+7

dev_dependencies:
  test: ^1.6.0
