name: at_end2end_test
publish_to: none
description: End to end tests for the at_client_sdk packages
version: 1.0.0

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  at_client:
    path: ../at_client

dev_dependencies:
  test: ^1.17.3
  coverage: ^1.0.3
  mockito: ^5.0.7
  lints: ^1.0.1
