name: at_client_mobile
description: A Flutter extension to the at_client library which adds support for mobile, desktop and IoT devices.
version: 3.0.3
repository: https://github.com/atsign-foundation/at_client_sdk
homepage: https://atsign.dev
documentation: https://atsign.dev/at_docs-dev_env/at_client_mobile/at_client_mobile/at_client_mobile-library.html

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.6.0
  flutter:
    sdk: flutter
  # flutter_keychain: ^2.0.1
  biometric_storage: ^2.0.2
  hive: ^2.0.4
  crypton: ^2.0.1
  at_client:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk.git
      path: at_client
      ref: desktop-compatible
  at_lookup: ^3.0.3
  at_commons: ^3.0.0
  at_utils: ^3.0.0

dependency_overrides:
  logging: ^1.0.0
  at_client:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk.git
      path: at_client
      ref: desktop-compatible
dev_dependencies:
  lints: ^1.0.1
  test: ^1.6.0
