name: at_client_mobile
description: Library for mobile app onboarding.
version: 1.0.0+10
repository: https://github.com/atsign-foundation/at_client_sdk
homepage: https://atsign.dev
documentation: https://atsign.dev/at_docs-dev_env/at_client_mobile/at_client_mobile/at_client_mobile-library.html
publish_to: none

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0
  flutter:
    sdk: flutter
  flutter_keychain: ^1.0.0
  hive: ^2.0.4
  crypton: ^2.0.1
  at_client:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk.git
      path: at_client
      ref: connection_issue
      version: ^1.0.1+9
  at_lookup:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: at_lookup
      ref: connection_issue
      version: ^1.0.0+9
  at_commons:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_commons
      ref: connection_issue
      version: ^1.0.1+8
  at_utils:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_utils
      ref: connection_issue
      version: ^1.0.1+8

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
