name: at_client_mobile
description: A Flutter extension to the at_client library which adds support for mobile, desktop and IoT devices.
version: 2.0.4
repository: https://github.com/atsign-foundation/at_client_sdk
homepage: https://atsign.dev
documentation: https://atsign.dev/at_docs-dev_env/at_client_mobile/at_client_mobile/at_client_mobile-library.html

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.6.0
  flutter:
    sdk: flutter
  flutter_keychain: ^2.0.1
  hive: ^2.0.4
  crypton: ^2.0.1
  at_client: ^2.0.3
  at_lookup: ^2.0.5
  at_commons: ^2.0.5
  at_utils: ^2.0.4
   
dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
