name: at_client_mobile
description: Library for mobile app onboarding.
version: 1.0.0+8
repository: https://github.com/atsign-foundation/at_client_sdk
homepage: https://atsign.dev
documentation: https://atsign.dev/at_docs-dev_env/at_client_mobile/at_client_mobile/at_client_mobile-library.html

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0
  flutter:
    sdk: flutter
  flutter_keychain: ^1.0.0
  hive: ^1.3.0
  crypton: ^1.1.0
  at_client: ^1.0.1+7
  at_lookup: ^1.0.0+5
  at_commons: ^1.0.1+5
  at_utils: ^1.0.1+5

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
