# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: at_client_sdk

on:
  pull_request:
    branches:
      - master
      - prod_staging
      - dev_env
      - dev_env_staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      # Install dependencies in at_client library
      - name: Install dependencies in at_client
        working-directory: at_client
        run: dart pub get

      # Run analyzer in at_client library
      - name: Analyze project source in at_client
        working-directory: at_client
        run: dart analyze

      # Run unit tests
      - name: Run unit tests
        working-directory: at_client
        run: dart test

      - name: Installing Flutter
        uses: britannio/action-install-flutter@v1.0
        with:
          version: stable

      - name: Installing dependencies
        working-directory: at_client_mobile
        run: flutter pub get

      - name: flutter analyze
        working-directory: at_client_mobile
        run: flutter analyze
